"""This module contains internal functions for working with DistillerSR API
requests."""

import io
import requests
import pandas as pd
from json import JSONDecodeError

from pystiller._utils import _checks, _data


def _perform_authentication_request(distiller_instance_url, distiller_key,
                                    timeout=1800):
    """Build and execute an authentication request for the DistillerSR API.

    This helper function configures and sends a GET authentication request to
    the DistillerSR API, setting the necessary headers and authentication key.
    It then performs the request and returns the corresponding response data.

    Args:
        distiller_instance_url (str): The URL of the DistillerSR instance.
        distiller_key (str): The personal access key generated in DistillerSR.
        timeout (int, optional): The maximum number of seconds to wait for the
            authentication response. Defaults to 1800 seconds (30 minutes).

    Returns:
        class (requests.Response): The HTTP response object returned by
            the request.
    """

    _checks._require_type(value=distiller_instance_url, expected_type=str)
    _checks._require_type(value=distiller_key, expected_type=str)
    _checks._require_type(value=timeout, expected_type=int)

    request_headers_ = {
        "Authorization": f"Key {distiller_key}",
        "Content-Type": "application/octet-stream"
    }

    response_ = requests.post(
        f"{distiller_instance_url}/auth",
        headers=request_headers_,
        timeout=timeout)

    return response_


def _perform_service_request(service_url, distiller_token, body=None,
                             timeout=1800):
    """Build and execute a service request to the DistillerSR API.

    This helper function configures and sends a service request to the
    DistillerSR API, setting the necessary headers and authentication key.
    It then performs the request and returns the corresponding response data.

    Args:
        service_url (str): The URL of the service endpoint.
        distiller_token (str): The personal access token generated by the
            authentication request.
        body (dict, optional): A dictionary containing the body parameters to
            be encoded into JSON format.
        timeout (int, optional): The maximum number of seconds to wait for the
            service response. Defaults to 1800 seconds (30 minutes).

    Returns:
        class (requests.Response): The HTTP response object returned by
            the request.
    """

    _checks._require_type(value=service_url, expected_type=str)
    _checks._require_type(value=distiller_token, expected_type=str)
    if body is not None:
        _checks._require_type(value=body, expected_type=dict)
    _checks._require_type(value=timeout, expected_type=int)

    request_headers_ = {
        "Authorization": f"Bearer {distiller_token}"
    }

    if body is None:
        request_headers_["Content-Type"] = "application/octet-stream"

        response_ = requests.get(
            url=service_url,
            headers=request_headers_,
            timeout=timeout)

    else:
        request_headers_["Content-Type"] = "application/json"

        response_ = requests.post(
            url=service_url,
            headers=request_headers_,
            json=body,
            timeout=timeout)

    return response_


def _handle_http_errors(response, error_message="API request failed"):
    """Handle non-successful HTTP responses from the DistillerSR API.

    This helper function checks whether an HTTP response from the DistillerSR
    API indicates success (status code 200). If the response contains any other
    status code, it raises a formatted error.

    Args:
        response (requests.Response): The HTTP response object.
        error_message (str, optional): The error message to be displayed.

    Raises:
        requests.exceptions.HTTPError: If the request was not successful.

    Returns:
        None: The function returns nothing if the request was successful.
    """

    _checks._require_type(value=response, expected_type=requests.Response)
    _checks._require_type(value=error_message, expected_type=str)

    if response.status_code != 200:
        raise requests.HTTPError(f"{error_message}\n(HTTP " +
                                 f"{response.status_code})")


def _parse_json_response(response,
                         error_message="Failed to parse JSON response",
                         flatten=False):
    """Parse a JSON API response.

    This helper function parses the JSON body of an API response. If the API
    response body cannot be parsed as valid JSON, the function raises an error.

    Args:
        response (requests.Response): The HTTP response object.
        error_message (str, optional): The message to display in case of
            errors.
        flatten (bool, optional): If True, flattens the response body into a
            data frame. Defaults to False.

    Raises:
        JSONDecodeError: If the response body can not be parsed as valid JSON.

    Returns:
        pd.DataFrame: A Pandas DataFrame representing the parsed JSON response.
    """

    _checks._require_type(value=response, expected_type=requests.Response)
    _checks._require_type(value=error_message, expected_type=str)

    try:
        response_data_ = response.json()
        if flatten:
            response_data_ = _data._flatten(response_data_)
    except (JSONDecodeError, KeyError) as e_:
        raise JSONDecodeError(f"{error_message}\n{e_.msg}",
                              e_.doc, e_.pos)

    return response_data_


def _parse_csv_response(response,
                        error_message="Failed to parse CSV response"):
    """Parse a CSV API response.

    This helper function parses the CSV body of an API response. If the API
    response body cannot be parsed as valid CSV, the function raises an error.

    Args:
        response (requests.Response): The HTTP response object.
        error_message (str, optional): The message to display in case of errors.

    Raises:
        ValueError: If the response body can not be parsed as valid CSV.

    Returns:
        pd.DataFrame: A dictionary representing the parsed CSV response.
    """

    _checks._require_type(value=response, expected_type=requests.Response)
    _checks._require_type(value=error_message, expected_type=str)

    try:
        response_csv_ = pd.read_csv(io.StringIO(response.text))
    except Exception as e_:
        raise ValueError(f"{error_message}\n{str(e_)}")

    return response_csv_


def _parse_xlsx_response(response,
                         error_message="Failed to parse XLSX response"):
    """Parse an XLSX API response.

    This helper function parses the XLSX body of an API response. If the API
    response body cannot be parsed as valid XLSX, the function raises an error.

    Args:
        response (requests.Response): The HTTP response object.
        error_message (str, optional): The message to display in case of errors.

    Raises:
        ValueError: If the response body can not be parsed as valid XLSX.

    Returns:
        pd.DataFrame: A dictionary representing the parsed XLSX response.
    """

    _checks._require_type(value=response, expected_type=requests.Response)
    _checks._require_type(value=error_message, expected_type=str)

    try:
        response_xlsx_ = pd.read_excel(io.BytesIO(response.content))
    except Exception as e_:
        raise ValueError(f"{error_message}\n{str(e_)}")

    return response_xlsx_
